---
- hosts: localhost
  become: yes

  tasks:
    - name: Install Docker
      apt:
       name: docker
       state: present

    - name: Install python dependencies
      package:
        update_cache: yes 
        name: python3-pip
        state: latest

    - name: Install Docker SDK for Python
      pip:
       name: docker
       executable: pip3

    - name: Create a network
      community.docker.docker_network:
        name: appnetwork

    - name: Build Nginx container 
      community.docker.docker_image:
        build: 
          path: ./nginx
        name: nginx
        source: build 

    - name: Build App container 
      community.docker.docker_image:
        build: 
          path: ./app
        name: flaskapp
        source: build 
    
    - name: Run App
      docker_container:
         name: flaskapp
         image: flaskapp:latest
         state: started
         exposed_ports: 5000
         networks:
           - name: appnetwork
    
    - name: Run Nginx
      docker_container:
         name: nginx
         image: nginx:latest
         state: started
         published_ports: "80:80"
         exposed_ports: 80
         networks:
           - name: appnetwork
