---
- hosts: containers
  become: yes

  tasks:
    - name: Install Docker
      apt:
       name: docker
       state: present
       
    - name: Install Docker.io 
      apt:
       name: docker.io
       state: present
       
    - name: Install python dependencies
      package:
        update_cache: yes 
        name: python3-pip
        state: latest

    - name: Install Docker SDK for Python
      pip:
       name: docker
       executable: pip3

    - name: Create a network
      community.docker.docker_network:
        name: appnetwork

    - name: Copy Nginx files
      ansible.builtin.copy:
        src: ./nginx
        dest: /home/dev

    - name: Copy Flask files
      ansible.builtin.copy:
        src: ./flask
        dest: /home/dev

    - name: Build Nginx container 
      community.docker.docker_image:
        build: 
          path: /home/dev/nginx/
        name: nginx
        source: build 

    - name: Build App container 
      community.docker.docker_image:
        build: 
          path: /home/dev/flask/
        name: flask
        source: build 
    
    - name: Run App
      docker_container:
         name: flask
         image: flask
         state: started
         exposed_ports: 5000
         networks:
           - name: appnetwork
    
    - name: Run Nginx
      docker_container:
         name: nginx
         image: nginx
         state: started
         published_ports: "80:80"
         exposed_ports: 80
         networks:
           - name: appnetwork
